select * from INFORMATION_SCHEMA.ROUTINES where ROUTINE_TYPE = 'PROCEDURE' order by SPECIFIC_NAME

/*



--PROCESO DE MIGRAGION--
USP_Obligaciones_MigracionTP_CtasPorCobrar_IU_MigrarDataPorAnio
USP_Obligaciones_Pagos_MigracionTP_CtasPorCobrar_IU_MigrarDataPorAnio

USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_61_MigracionMatricula
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_62_MigracionCabecera
USP_Obligaciones_Pagos_MigracionTP_U_Validar_63_MigracionCabecera



--PROCESO DE VALIDACIONES POR ID--
USP_Obligaciones_ObligacionCab_MigracionTP_U_InicializarEstadoValidacionPorID
USP_Obligaciones_ObligacionDet_MigracionTP_U_InicializarEstadoValidacionPorID
USP_Obligaciones_Pagos_MigracionTP_U_InicializarEstadoValidacionPorID

USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_24_ExisteAlumnoPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_26_AnioNumericoPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_27_PeriodoPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_28_FechaVencimientoCuotaPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_32_ObligacionCuotaPagoMigradaPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_34_ProcedenciaCuotaPagoPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_40_ObligacionSinDetallePorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_59_ObligacionRepetidaPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_36_ConceptoPagoMigradoPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_54_PagoEnObligacionNoPagadoPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_60_SinPagoEnObligacioPagada
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_29_ExisteEnDestinoPorOblID

USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_35_ConceptoPagoPorOblID
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_43_AnioDetalleNumericoPorOblID
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_33_ConceptoPagoMigradoPorOblID
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_15_AnioDetalleAnioConceptoPorOblID
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_17_PeriodoDetallePeriodoConceptoPorOblID
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_44_PeriodoDetalleEquivPeriodoCtasPorOblID
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_42_CuotaDetalleCuotaConceptoPorOblID
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_49_MontoDetalleMontoCabPorOblID

USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_39_DetalleObservadoPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_37_ObservacionAnioDetallePorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_38_ObservacionPeriodoDetallePorOblID

USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_25_ObligacionCabIDPorOblID

USP_Obligaciones_Pagos_MigracionTP_U_Validar_57_CabObligacionObservadaPorOblID
USP_Obligaciones_Pagos_MigracionTP_U_Validar_56_DetalleObservadoPorOblID
USP_Obligaciones_Pagos_MigracionTP_U_Validar_53_MontoPagadoDetallePorID
USP_Obligaciones_Pagos_MigracionTP_U_Validar_55_ExisteEnDestinoConOtroBancoPorID

--PROCESO DE MIGRAGION POR ID--
USP_Obligaciones_MigracionTP_CtasPorCobrar_IU_MigrarDataPorID
USP_Obligaciones_Pagos_MigracionTP_CtasPorCobrar_IU_MigrarDataPorID

USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_61_MigracionMatriculaPorOblID
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_62_MigracionCabeceraPorOblID
USP_Obligaciones_Pagos_MigracionTP_U_Validar_63_MigracionCabeceraPorOblID



USP_Alumnos_MigracionTP_IU_CopiarTabla
USP_Alumnos_MigracionTP_Repositorio_IU_MigrarDataPorAnio
USP_Alumnos_MigracionTP_Repositorio_IU_MigrarDataPorCodigo
USP_Alumnos_MigracionTP_U_ActualizarRegistro
USP_Alumnos_MigracionTP_U_InicializarEstadoValidacion
USP_Alumnos_MigracionTP_U_InicializarEstadoValidacionPorAlumnoID
USP_Alumnos_MigracionTP_U_RegistrarObservacionPorAlumno
USP_Alumnos_MigracionTP_U_RemoverObservacionPorAlumno
USP_Alumnos_MigracionTP_U_Validar_01_CaracteresEspeciales
USP_Alumnos_MigracionTP_U_Validar_01_CaracteresEspecialesPorAlumnoID
USP_Alumnos_MigracionTP_U_Validar_02_CodigosRepetidos
USP_Alumnos_MigracionTP_U_Validar_02_CodigosRepetidosPorAlumnoID
USP_Alumnos_MigracionTP_U_Validar_21_CodigoCarrera
USP_Alumnos_MigracionTP_U_Validar_21_CodigoCarreraPorAlumnoID
USP_Alumnos_MigracionTP_U_Validar_22_AnioIngreso
USP_Alumnos_MigracionTP_U_Validar_22_AnioIngresoPorAlumnoID
USP_Alumnos_MigracionTP_U_Validar_23_ModalidadIngreso
USP_Alumnos_MigracionTP_U_Validar_23_ModalidadIngresoPorAlumnoID
USP_Alumnos_MigracionTP_U_Validar_30_CorrespondenciaNumDocumentoPersona
USP_Alumnos_MigracionTP_U_Validar_30_CorrespondenciaNumDocumentoPersonaPorAlumnoID
USP_Alumnos_MigracionTP_U_Validar_31_SexoDiferenteMismoDocumento
USP_Alumnos_MigracionTP_U_Validar_31_SexoDiferenteMismoDocumentoPorAlumnoID
USP_Alumnos_MigracionTP_U_Validar_41_CorrespondenciaNumDocRepositorioPersona
USP_Alumnos_MigracionTP_U_Validar_41_CorrespondenciaNumDocRepositorioPersonaPorAlumnoID
USP_Alumnos_MigracionTP_U_Validar_45_CodigosRemovidos
USP_Alumnos_MigracionTP_U_Validar_45_CodigosRemovidosPorAlumnoID
USP_Alumnos_MigracionTP_U_Validar_47_SexoDiferenteMismoAlumno
USP_Alumnos_MigracionTP_U_Validar_47_SexoDiferenteMismoAlumnoPorAlumnoID
USP_Alumnos_MigracionTP_U_Validar_48_DocumentoDiferenteMismoAlumno
USP_Alumnos_MigracionTP_U_Validar_48_DocumentoDiferenteMismoAlumnoPorAlumnoID
USP_Alumnos_Repositorio_I_InsertarAlumnoTablaAlumno
USP_Alumnos_Repositorio_U_ActualizarTablaAlumno
USP_Alumnos_Repositorio_U_ActualizarTablaPersona
USP_Obligaciones_ConceptoPago_CtasPorCobrar_IU_GrabarTablaCatalogoConceptos
USP_Obligaciones_ConceptoPago_MigracionTP_CtasPorCobrar_IU_MigrarData
USP_Obligaciones_ConceptoPago_MigracionTP_U_ActualizarEquivalenciaCtasID
USP_Obligaciones_ConceptoPago_MigracionTP_U_ActualizarEquivalenciaDestino
USP_Obligaciones_ConceptoPago_MigracionTP_U_AsignarIdEquivalencias
USP_Obligaciones_ConceptoPago_MigracionTP_U_InicializarEstadoValidacion
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_12_RepetidoActivo
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_13_RepetidosEliminado
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_14_SinAnio
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_15_AnioDiferenteCuotaPago
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_16_SinPeriodoAsignado
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_17_ConPeriodoDiferenteCuotaPago
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_18_SinCuotaPago
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_19_SinCuotaPagoMigrada
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_20_IngresadoFuenteExterna
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_45_Eliminados
USP_Obligaciones_ConceptoPago_MigracionTP_U_Validar_46_TipoObligacion
USP_Obligaciones_ConceptoPago_MigracionTP_U_VerificarExisteEnCtas
USP_Obligaciones_ConceptoPago_MigracionTP_U_VerificarMigracionEnCtas
USP_Obligaciones_ConceptoPago_TemporalPagos_MigracionTP_IU_CopiarTabla
USP_Obligaciones_CuotaPago_MigracionTP_CtasPorCobrar_I_MigrarCtaDeposito
USP_Obligaciones_CuotaPago_MigracionTP_CtasPorCobrar_IU_MigrarData
USP_Obligaciones_CuotaPago_MigracionTP_U_InicializarEstadoValidacion
USP_Obligaciones_CuotaPago_MigracionTP_U_Validar_03_RepetidosActivo
USP_Obligaciones_CuotaPago_MigracionTP_U_Validar_04_RepetidosEliminado
USP_Obligaciones_CuotaPago_MigracionTP_U_Validar_05_VariosAniosAsignados
USP_Obligaciones_CuotaPago_MigracionTP_U_Validar_06_SinAnioAsignado
USP_Obligaciones_CuotaPago_MigracionTP_U_Validar_07_VariosPeriodosAsignados
USP_Obligaciones_CuotaPago_MigracionTP_U_Validar_08_SinPeriodoAsignado
USP_Obligaciones_CuotaPago_MigracionTP_U_Validar_09_VariasCategoriasAsignadas
USP_Obligaciones_CuotaPago_MigracionTP_U_Validar_10_SinCategoriaAsingada
USP_Obligaciones_CuotaPago_MigracionTP_U_Validar_45_Eliminados
USP_Obligaciones_CuotaPago_MigracionTP_U_Validar_50_RepetidoConDiferentesProcedencias
USP_Obligaciones_CuotaPago_MigracionTP_U_ValidarExisteCtaDepoEnCtasxCobrar
USP_Obligaciones_CuotaPago_MigracionTP_U_ValidarExisteProcesoEnCtasxCobrar
USP_Obligaciones_CuotaPago_MigracionTP_U_ValidarExisteRegistroEnCtasxCobrar
USP_Obligaciones_CuotaPago_TemporalPagos_MigracionTP_IU_CopiarTabla

USP_Obligaciones_MigracionTP_CtasPorCobrar_I_GrabarDetObligPorObligacionID
USP_Obligaciones_MigracionTP_CtasPorCobrar_I_GrabarMatriculaPorObligacionID
USP_Obligaciones_MigracionTP_CtasPorCobrar_U_GrabarMatriculaPorObligacionID




--PROCESO DE COPIA DE TABLAS---
USP_Obligaciones_ObligacionCab_TemporalPagos_MigracionTP_IU_CopiarTabla
USP_Obligaciones_ObligacionDet_TemporalPagos_MigracionTP_IU_CopiarTabla
USP_Obligaciones_Pagos_TemporalPagos_MigracionTP_IU_CopiarTabla

USP_Obligaciones_ObligacionDet_MigracionTP_U_AsignarObligacionCabID
USP_Obligaciones_Pagos_MigracionTP_U_AsignarObligacionID

--PROCESO DE VALIDACIONES premigracion--
USP_Obligaciones_ObligacionCab_MigracionTP_U_InicializarEstadoValidacion
USP_Obligaciones_ObligacionDet_MigracionTP_U_InicializarEstadoValidacion
USP_Obligaciones_Pagos_MigracionTP_U_InicializarEstadoValidacion

USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_24_ExisteAlumno
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_26_AnioNumerico
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_27_Periodo
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_28_FechaVencimientoCuota
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_32_ObligacionCuotaPagoMigrada
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_34_ProcedenciaCuotaPago
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_40_ObligacionSinDetalle
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_59_ObligacionRepetida
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_36_ConceptoPagoMigrado
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_54_PagoEnObligacionNoPagado
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_60_SinPagoEnObligacioPagadaPorOblID
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_29_ExisteEnDestino

USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_58_SinObligacionCabID
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_35_ConceptoPago
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_43_AnioDetalleNumerico
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_33_ConceptoPagoMigrado
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_15_AnioDetalleAnioConcepto
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_17_PeriodoDetallePeriodoConcepto
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_44_PeriodoDetalleEquivPeriodoCtas
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_42_CuotaDetalleCuotaConcepto
USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_49_MontoDetalleMontoCab

USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_39_DetalleObservado
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_37_ObservacionAnioDetalle
USP_Obligaciones_ObligacionCab_MigracionTP_U_Validar_38_ObservacionPeriodoDetalle

USP_Obligaciones_ObligacionDet_MigracionTP_U_Validar_25_ObligacionCabID

USP_Obligaciones_Pagos_MigracionTP_U_Validar_57_CabObligacionObservada
USP_Obligaciones_Pagos_MigracionTP_U_Validar_56_DetalleObservado
USP_Obligaciones_Pagos_MigracionTP_U_Validar_52_SinObligacionID
USP_Obligaciones_Pagos_MigracionTP_U_Validar_53_MontoPagadoDetalle
USP_Obligaciones_Pagos_MigracionTP_U_Validar_55_ExisteEnDestinoConOtroBanco





USP_Shared_ControlTabla_MigracionTP_IU_RegistrarCopiados
USP_Shared_ControlTabla_MigracionTP_IU_RegistrarMigracion
USP_Shared_ControlTabla_MigracionTP_IU_RegistrarValidacion
USP_Tasas_ConceptoPago_MigracionTP_U_Validar_51_TipoObligacion
USP_Tasas_CuotaPago_TemporalTasas_MigracionTP_IU_CopiarTabla

*/