USE BD_OCEF_MigracionTP
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TR_Ec_Obl' AND COLUMN_NAME = 'B_MigradoPago')
BEGIN
	ALTER TABLE [dbo].[TR_Ec_Obl]
		ADD B_MigradoPago	bit  NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TR_Ec_Obl' AND COLUMN_NAME = 'D_FecMigradoPago')
BEGIN
	ALTER TABLE [dbo].[TR_Ec_Obl]
		ADD D_FecMigradoPago	datetime  NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TR_Ec_Obl' AND COLUMN_NAME = 'B_Correcto')
BEGIN
	ALTER TABLE [dbo].[TR_Ec_Obl]
		ADD B_Correcto	bit  NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TR_Cp_Pri' AND COLUMN_NAME = 'B_Correcto')
BEGIN
	ALTER TABLE [dbo].[TR_Cp_Pri]
		ADD B_Correcto	bit  NULL
END
GO




IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TR_Ec_Det' AND COLUMN_NAME = 'B_MigradoPago')
BEGIN
	ALTER TABLE [dbo].[TR_Ec_Det]
		ADD B_MigradoPago	bit  NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TR_Ec_Det' AND COLUMN_NAME = 'D_FecMigradoPago')
BEGIN
	ALTER TABLE [dbo].[TR_Ec_Det]
		ADD D_FecMigradoPago	datetime  NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TR_Ec_Det' AND COLUMN_NAME = 'D_FecMigradoPago')
BEGIN
	ALTER TABLE [dbo].[TR_Ec_Det]
		ADD D_FecMigradoPago	bit  NULL
END
GO


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TC_CatalogoObservacion' AND COLUMN_NAME = 'T_ObservDesc')
BEGIN
	ALTER TABLE [dbo].[TC_CatalogoObservacion]
		ALTER COLUMN T_ObservDesc	varchar(150)  NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TC_CatalogoObservacion' AND COLUMN_NAME = 'I_TablaID')
BEGIN
	ALTER TABLE [dbo].[TC_CatalogoObservacion]
		ADD I_TablaID	varchar(150)  NULL
END
GO