USE BD_UNFV_Repositorio
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TC_Persona' AND COLUMN_NAME = 'I_MigracionRowID')
BEGIN
	ALTER TABLE [dbo].[TC_Persona]
		ADD I_MigracionRowID	int  NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TC_Persona' AND COLUMN_NAME = 'I_MigracionTablaID')
BEGIN
	ALTER TABLE [dbo].[TC_Persona]
		ADD I_MigracionTablaID	int  NULL
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TC_Alumno' AND COLUMN_NAME = 'I_MigracionRowID')
BEGIN
	ALTER TABLE [dbo].[TC_Alumno]
		ADD I_MigracionRowID	int  NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TC_Alumno' AND COLUMN_NAME = 'I_MigracionTablaID')
BEGIN
	ALTER TABLE [dbo].[TC_Alumno]
		ADD I_MigracionTablaID	int  NULL
END
GO
